高考学考:
  高中学业考: https://www.shmeea.edu.cn/page/02100/index.html
  秋季高考: https://www.shmeea.edu.cn/page/02200/index.html
  春季高考: https://www.shmeea.edu.cn/page/02300/index.html
  三校生高考: https://www.shmeea.edu.cn/page/02400/index.html
  艺体类加试: https://www.shmeea.edu.cn/page/02500/index.html
  专科自主招生: https://www.shmeea.edu.cn/page/02600/index.html
  其他考试: https://www.shmeea.edu.cn/page/02700/index.html
  中职校学业考: https://www.shmeea.edu.cn/page/21000/index.html
中考中招:
  中招政策: https://www.shmeea.edu.cn/page/03100/index.html
  招生公示: https://www.shmeea.edu.cn/page/03200/index.html
  报名须知: https://www.shmeea.edu.cn/page/03300/index.html
  志愿填报: https://www.shmeea.edu.cn/page/03400/index.html
  考试规定: https://www.shmeea.edu.cn/page/03500/index.html
  招生录取: https://www.shmeea.edu.cn/page/03600/index.html
研考成考:
  研究生招生考试: https://www.shmeea.edu.cn/page/05100/index.html
  成人高考招生考试: https://www.shmeea.edu.cn/page/05200/index.html
  同等学力人员申请硕士学位外国语水平和学科综合水平全国统一考试: https://www.shmeea.edu.cn/page/05900/index.html
自学考试:
  自考新闻: https://www.shmeea.edu.cn/page/04100/index.html
  考试日程: https://www.shmeea.edu.cn/page/04200/index.html
  政策法规: https://www.shmeea.edu.cn/page/04300/index.html
  大纲教材: https://www.shmeea.edu.cn/page/04400/index.html
证书考试:
  全国大学英语四、六级考试（CET）: https://www.shmeea.edu.cn/page/05400/index.html
  全国中小学教师资格考试: https://www.shmeea.edu.cn/page/05500/index.html
  全国英语等级考试（PETS）: https://www.shmeea.edu.cn/page/05600/index.html
  全国计算机等级考试（NCRE）: https://www.shmeea.edu.cn/page/05700/index.html
  上海市高等学校信息技术水平考试: https://www.shmeea.edu.cn/page/05800/index.html
  普通话水平测试: https://www.shmeea.edu.cn/page/pthspcs/index.html
  上海市高等学校教师资格专业课程考试: https://www.shmeea.edu.cn/page/gdxxjszg/index.html
